on:
  workflow_dispatch:

name: App Build and Package

jobs:
  build:
    name: Compile
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: |
          echo "Compile application"
          javac -version
