on:
  workflow_dispatch:

name: App Build, Package and Deploy

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  IMAGE_NAME: brainupgrade/nodejsappdocker:latest

jobs:
  build-and-deploy:
    runs-on: 
      group: 'Default'
      labels: ['Linux','codespaces','self-hosted']
    steps:
    - uses: actions/checkout@v2

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Login to DockerHub
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_PASSWORD }}

    # Build and push Docker image
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{env.IMAGE_NAME}}

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.AWS_EC2_SSH_KEY }}
        script: |
          docker pull ${{ env.IMAGE_NAME }}
          docker stop app || true
          docker rm app || true
          docker run -d --name app ${{ env.IMAGE_NAME }}        